### PR TITLE
Fixed #220 and added bug fix for problem when SideWaffle tries to fetch sources when it is already fetching them

### LINKED ISSUE #220: Better support for custom URLs
For the dynamic templates the templateSource.json file is currently being stored under the extension directory. The side effect of that is that when the extension is uninstalled/installed all customizations are removed. It would be better to.

 - [x] Store the templateSource.json file in the ```%localappdata%/SIdeWaffle``` folder so that customizations are preserved across versions. We should consider if we want to place it in a version folder or in the root. If in the root if there are breaking changes we should make sure that we "upgrade" the format of the file
 - [x] Have a button on the config page to "Reset Defaults" in the templateSources.json file

### PR DESCRIPTION
**Pull request by RandomlyKnighted**

### CODE REVIEW

**Comment by RandomlyKnighted** [comment]
Hopefully, I didn't miss anything..that DynamicTemplateBuilder file starts getting confusing after you scroll up and down a few times hunting for specific methods to update :smile:

File: TemplatePack/Tooling/DynamicTemplateBuilder.cs [hunk 1]
```diff
@@ -140,34 +146,41 @@ public class DynamicTemplateBuilder {
...
-                if (!Directory.Exists(template.TemplateSourceRoot) && template.Source.Enabled)
-                {
-                    FetchSourceLocally(template.Source, template.TemplateSourceRoot);
-                    BuildTemplate(template);
-                    CopyTemplatesToExtensionsFolder(template);
-                    TouchUpgradeLog();
-                }
-                else if (Directory.Exists(template.TemplateSourceRoot) && template.Source.Enabled)
+
+            if (CheckIfAlreadyBuildingSources())
```
Comment (sayedihashimi) [inline TemplatePack/Tooling/DynamicTemplateBuilder.cs]: Should this be if( !CheckIfAlreadyBuildingSources() ) ?

Comment (RandomlyKnighted) [inline TemplatePack/Tooling/DynamicTemplateBuilder.cs]: Yep, just added a commit to fix that.

File: TemplatePack/Tooling/DynamicTemplateBuilder.cs [hunk 2]
```diff
@@ -140,34 +146,41 @@ public class DynamicTemplateBuilder {
...
-                if (!Directory.Exists(template.TemplateSourceRoot) && template.Source.Enabled)
-                {
-                    FetchSourceLocally(template.Source, template.TemplateSourceRoot);
-                    BuildTemplate(template);
-                    CopyTemplatesToExtensionsFolder(template);
-                    TouchUpgradeLog();
-                }
-                else if (Directory.Exists(template.TemplateSourceRoot) && template.Source.Enabled)
+
+            if (!CheckIfAlreadyBuildingSources())
```
Comment (sayedihashimi) [inline TemplatePack/Tooling/DynamicTemplateBuilder.cs]: The implementation of CheckIfAlreadyBuildingSources is different than we discussed and sub-optimal.

What we discussed was:
1. Check if the file exists, if so its building and return true so template build skipped
1. If not building, start processtemplates()
1. Drop a file indicating a template build is happening
1. When template build completes delete the file

We should also handle the case if there was a crash during template build and the file isn't deleted. A simple way to do that is: If the file exists and was last modified more than an hour ago assume template build has completed.

To implement it, update and rename to IsBuildingDynamicTemplates()

// check if file exists and is more than 1 hr old, if so delete it

// return true if file exists

Comment (sayedihashimi) [inline TemplatePack/Tooling/DynamicTemplateBuilder.cs]: When you implement it, it should be like the following.

try{
// create file
// build templates
}
finally{
// delete the file
}

_sorry about lack of formatting, typing on phone_

File: TemplatePack/Tooling/DynamicTemplateBuilder.cs [hunk 3]
```diff
@@ -140,34 +146,41 @@ public class DynamicTemplateBuilder {
...
+                var settings = GetTemplateSettingsFromJson();
+                var templateLocalInfo = GetLocalInfoFor(settings.Sources);
+
+                // see if the source exists locally, if not then get it
+                foreach (var template in templateLocalInfo)
                 {
-                    if (CheckIfTimeToUpdateSources())
+                    if (!Directory.Exists(template.TemplateSourceRoot) && template.Source.Enabled)
                     {
                         FetchSourceLocally(template.Source, template.TemplateSourceRoot);
```
Comment (sayedihashimi) [inline TemplatePack/Tooling/DynamicTemplateBuilder.cs]: There is some code duplication here which is not ideal.
One easy way to avoid the duplication here. Put the five lines into an action (func without a return value) then call that in the if.

Fyi I'm commenting like this because I know you're interested in learning. To be clear I'd merge this, but just trying to give you extra pointers.

Comment (RandomlyKnighted) [inline TemplatePack/Tooling/DynamicTemplateBuilder.cs]: I'm not sure that I see what duplication you're talking about, because everything is just function calls.

File: TemplatePack/Tooling/DynamicTemplateBuilder.cs (hunk 2 above)
Comment (RandomlyKnighted) [inline TemplatePack/Tooling/DynamicTemplateBuilder.cs]: Its fine, I think I changed it when I was going off the idea of using that other log file then forgot what our original idea was. I'll have this fixed soon.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi when looking up func I read that Func actually returns a value but Action does not so I used that in my code. Is this what you were talking about?

File: TemplatePack/Tooling/DynamicTemplateBuilder.cs [hunk 4]
```diff
@@ -140,36 +146,59 @@ public class DynamicTemplateBuilder {
...
+            // Drop a file indicating a template build is happening
+            try
+            {
+                if (!File.Exists(this.BuildingTemplatesLogFilePath))
                 {
-                    FetchSourceLocally(template.Source, template.TemplateSourceRoot);
-                    BuildTemplate(template);
-                    CopyTemplatesToExtensionsFolder(template);
-                    TouchUpgradeLog();
+                    using (File.Create(this.BuildingTemplatesLogFilePath))
```
Comment (sayedihashimi) [inline TemplatePack/Tooling/DynamicTemplateBuilder.cs]: using (File.Create(filename)) ;

Will work here as well so we can leave off the braces.

File: TemplatePack/Tooling/DynamicTemplateBuilder.cs [hunk 5]
```diff
@@ -140,36 +146,59 @@ public class DynamicTemplateBuilder {
...
 
+            finally
+            {
+                File.Delete(BuildingTemplatesLogFilePath); // When template build completes delete the file
+            }
+
             UpdateStatusBar("Finished updating project and item templates");
         }
 
+        public void FetchSources(TemplateLocalInfo template)
```
Comment (sayedihashimi) [inline TemplatePack/Tooling/DynamicTemplateBuilder.cs]: There is no need for this function. The point of creating the action was to avoid a function :) Just declare this as a lambda in your action declaration.

File: TemplatePack/Tooling/DynamicTemplateBuilder.cs [hunk 6]
```diff
@@ -313,30 +342,67 @@ public void WriteJsonTemplateSettings(RemoteTemplateSettings settings)
...
+                // Download and build the latest templates from their source
+                ProcessTemplates();
             }
+        }
+
+        public bool IsBuildingDynamicTemplates()
+        {
 
-            // Delete the Output folder from the Extension directory
-            if (Directory.Exists(OutputPath))
```
Comment (sayedihashimi) [inline TemplatePack/Tooling/DynamicTemplateBuilder.cs]: Please add braces to if

File: TemplatePack/Tooling/DynamicTemplateBuilder.cs (hunk 5 above)
Comment (RandomlyKnighted) [inline TemplatePack/Tooling/DynamicTemplateBuilder.cs]: Alright I'll see what I can do. Also I just realized that while I did call performFetch twice I didn't actually remove the remainder of the old code from the if statement.

File: TemplatePack/Tooling/DynamicTemplateBuilder.cs [hunk 7]
```diff
@@ -313,30 +337,67 @@ public void WriteJsonTemplateSettings(RemoteTemplateSettings settings)
...
+                }
+
+                // Download and build the latest templates from their source
+                ProcessTemplates();
             }
+        }
 
-            // Delete the Output folder from the Extension directory
-            if (Directory.Exists(OutputPath))
+        public bool IsBuildingDynamicTemplates()
```
Comment (sayedihashimi) [inline TemplatePack/Tooling/DynamicTemplateBuilder.cs]: I haven't had a chance to actually test this yet. I should be able to tomorrow. If it works you can go ahead and merge if you like.

I know you're trying to learn so I'm giving more info.

The implementation of this is similar to my pseudo code but different in a less desirable way.

The way I would have structured this code would have been:

```
// check if file exists and is more than 1 hr old, if so delete it

// return true if file exists
```

In your case you have

```
// if the file exists and is older than 1 hour delete it
    // then return false

// if the file exists
    // then return true
    // else return false
```

In your implementation if the way to determine if building templates is updated then there are two branches of code that need to be updated. Instead just handle the special case (file exists and is older than 1 hour) and make it into a normal case (file doesn't exist).

The return statement can just return the value for File.Exists directly as well so that you just have a single return statement at the bottom and no additional if statements.

Comment (RandomlyKnighted) [inline TemplatePack/Tooling/DynamicTemplateBuilder.cs]: But if you just check to see if the file does not exists by returning the value for File.Exists then you're not handling the case for the file being older than one hour.

**Comment by sayedihashimi** [comment]
FYI I looked at this and there is some error related to the TemplateBuilder nuget pkg not being in the vsix. I thought for sure I made those changes. I will investigate.

**Comment by sayedihashimi** [comment]
I'm trying to figure out when the regression happened and how to fix it. I found when building that the .nupkg is included on commit [updating to 1.1.2-beta of templatebuilder](https://github.com/ligershark/side-waffle/commit/493bcfb16d1f8d43d1094debbc7dac0ab589a00d) but not in the previous commit [updating to 1.1.1 of templatebuilder](https://github.com/ligershark/side-waffle/commit/815e4c39f92290c323fed3a745a315bb76f4fec5)

From the diff I couldn't see exactly why. I will need to continue investigating.

**Comment by sayedihashimi** [comment]
There was some issue when TemplateBuilder was installed last. All I had to do was just uninstall and reinstall it. Fixed in 29ce0e0855ab161a0929237d8a234c3950ed3de2

**Comment by RandomlyKnighted** [comment]
Alright, I'll pull in the changes this evening.

**Comment by sayedihashimi** [comment]
Just tried the latest and I'm getting the following error.
sw-json-error

**Comment by sayedihashimi** [comment]
I fixed it and merged it.

**Comment by RandomlyKnighted** [comment]
What was causing the issue?

**Comment by sayedihashimi** [comment]
The code was trying to get the template file from the output folder instead of the install dir here is the commit ba0ac940c35bf4fecdbac76901e67ea5a3a57fc6
